version: "3.7"

services:
  backend:
    build:
     context: ./backend
     dockerfile: ./src/checkout/Dockerfile
    restart: always
    ports:
      - 5000:3000
    env_file:
      - .env
    volumes:
      - ./backend/src/checkout:/app
    links:
      - mariadb:mysql
    depends_on:
      - mariadb
    networks:
      - backend

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - backend

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      UPLOAD: 512M
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend: